import Image from "next/image";
import Link from "next/link";
import { ActionArrow } from "@/components/ActionArrow";
import styles from "./WebsitesServicePage.module.css";

const formats = [
  { number: "01", title: "Лендинг", text: "Для одного предложения, услуги или запуска. Помогает последовательно объяснить ценность и привести посетителя к заявке.", kind: "landing" },
  { number: "02", title: "Корпоративный сайт", text: "Для компании с несколькими направлениями, услугами или аудиториями. Собирает информацию в понятную структуру и ведёт к нужному разделу или обращению.", kind: "corporate" },
  { number: "03", title: "Каталог", text: "Для сложного ассортимента. Помогает найти категорию или товар, разобраться в характеристиках и отправить предметный запрос менеджеру.", kind: "catalog" },
] as const;

const creationStages = [
  { number: "01", title: "Бизнес, продукт, аудитория", text: "Разбираемся, что продаёт компания, кому и как принимает обращения." },
  { number: "02", title: "Структура и содержание", text: "Определяем страницы, разделы и материалы, которые помогают выбрать." },
  { number: "03", title: "Сценарии и прототип", text: "Собираем путь по сайту и проверяем логику до визуального решения." },
  { number: "04", title: "Дизайн", text: "Показываем главное, выстраиваем иерархию и точки действия." },
  { number: "05", title: "Desktop и mobile", text: "Разрабатываем сайт и его адаптивные состояния для разных экранов." },
  { number: "06", title: "Тестирование и запуск", text: "Проверяем основные сценарии, подключаем согласованные интеграции и запускаем." },
] as const;

function HeroRoute() {
  return <div className={styles.heroRoute} aria-label="Путь от предложения до работы менеджера">
    <div className={styles.heroRouteGrid} aria-hidden="true" />
    <p className={styles.routeEyebrow}>Как сайт работает на продажи</p>
    <div className={styles.offerCard}><span>01</span><strong>Предложение</strong><small>Что получает клиент</small></div>
    <div className={styles.choiceCard}><span>02</span><strong>Выбор</strong><i /><i /><i /></div>
    <div className={styles.contactCard}><span>03</span><strong>Обращение</strong><small>Форма · звонок · чат</small></div>
    <div className={styles.crmCard}><span>04</span><small>CRM</small><strong>Новый запрос</strong><em>Источник · выбор · контакт</em></div>
    <div className={styles.managerCard}><span>05</span><strong>Менеджер</strong><small>Продолжает работу</small></div>
    <i className={styles.heroRouteLine} aria-hidden="true" />
  </div>;
}

function FormatVisual({ kind }: { kind: (typeof formats)[number]["kind"] }) {
  if (kind === "landing") return <div className={styles.landingVisual} aria-hidden="true"><i /><i /><b /><span /></div>;
  if (kind === "corporate") return <div className={styles.corporateVisual} aria-hidden="true"><i /><i /><i /><b /><b /><b /></div>;
  return <div className={styles.catalogVisual} aria-hidden="true"><i /><i /><i /><i /><b /><b /><b /></div>;
}

export function WebsitesServicePage() {
  return <main id="main" className={styles.page}>
    <section className={styles.hero} aria-labelledby="websites-title"><div className={styles.container}>
      <nav className={styles.breadcrumbs} aria-label="Хлебные крошки"><Link href="/">Главная</Link><span aria-hidden="true">/</span><Link href="/services">Услуги</Link><span aria-hidden="true">/</span><span aria-current="page">Сайты</span></nav>
      <div className={styles.heroGrid}><div className={styles.heroCopy}><p className={styles.kicker}>Разработка сайтов для бизнеса</p><h1 id="websites-title">Сайты, которые приводят заявки.</h1><p className={styles.heroLead}>Проектируем и разрабатываем сайты под задачу бизнеса: объясняем предложение, ведём посетителя к целевому действию, передаём обращение в CRM и помогаем отделу продаж довести его до следующего этапа сделки.</p><div className={styles.heroActions}><a href="#contact-dialog" data-contact-dialog className={styles.primaryAction}>Обсудить новый сайт <ActionArrow /></a><Link href="#sales-route" className={styles.contextLink}>Посмотреть, как сайт работает на продажи</Link></div></div><HeroRoute /></div>
    </div></section>

    <section className={styles.salesArgument} aria-labelledby="sales-title"><div className={styles.container}><div className={styles.sectionHeading}><p className={styles.sectionIndex}>01 / Сайт и продажи</p><div><h2 id="sales-title">Сайт должен вести к продаже, а не просто рассказывать о компании.</h2><p>Посетитель приходит с вопросом: подходит ли ему ваш продукт, что выбрать и как сделать следующий шаг. Если сайт не отвечает на эти вопросы быстро, интерес заканчивается до обращения.</p></div></div><div className={styles.salesScene}><div className={styles.salesCopy}><p>Чтобы посетитель дошёл до заявки, на сайте должны работать три простые вещи.</p><span>Путь до обращения</span></div><ol className={styles.salesSteps}><li><span>01</span><div><h3>Понятно, что вы предлагаете</h3><p>Главное предложение и условия видны без долгого поиска.</p></div><i aria-hidden="true" /></li><li><span>02</span><div><h3>Легко выбрать нужное</h3><p>Структура, категории и содержание помогают сориентироваться.</p></div><i aria-hidden="true" /></li><li><span>03</span><div><h3>Просто обратиться</h3><p>Следующий шаг заметен там, где он нужен посетителю.</p></div><i aria-hidden="true" /></li></ol></div></div></section>

    <section className={styles.formats} aria-labelledby="formats-title"><div className={styles.container}><div className={styles.formatsHeading}><p className={styles.sectionIndex}>02 / Форматы сайтов</p><h2 id="formats-title">Создаём сайт под то, как продаёт ваш бизнес.</h2><p>Сайт собирается вокруг предложения, ассортимента и сценария покупки — от одного продукта до сложного каталога.</p></div><div className={styles.formatGrid}>{formats.map((format) => <article className={[styles.formatCard, styles[format.kind]].join(" ")} key={format.kind}><span className={styles.formatNumber}>{format.number}</span><FormatVisual kind={format.kind} /><div><h3>{format.title}</h3><p>{format.text}</p></div></article>)}</div><p className={styles.formatsNote}>Состав страниц и сценарии определяем после разбора вашего предложения и пути клиента.</p></div></section>

    <section className={styles.creationSection} id="sales-route" aria-labelledby="creation-title"><div className={styles.container}><div className={styles.creationHeader}><div><p className={styles.sectionIndex}>03 / Создание сайта</p><h2 id="creation-title">От задачи бизнеса — к работающему сайту.</h2></div><p>Собираем сайт вокруг продукта, структуры и будущей работы команды: от первого разбора до тестирования и запуска.</p></div><ol className={styles.creationRoute}>{creationStages.map((item, index) => <li key={item.number}><div className={styles.creationPreview} aria-hidden="true"><span>{item.number}</span><i /><i /><i /></div><div><h3>{item.title}</h3><p>{item.text}</p></div>{index < creationStages.length - 1 && <b className={styles.creationConnector} aria-hidden="true" />}</li>)}</ol><p className={styles.creationCaption}>Каждый этап уточняет следующий: так структура, дизайн и разработка работают как один сайт.</p></div></section>

    <section className={styles.technology} aria-labelledby="technology-title"><div className={styles.container}><div className={styles.sectionHeading}><p className={styles.sectionIndex}>04 / Технология</p><div><h2 id="technology-title">Подбираем технологию под бизнес, содержание и дальнейшее развитие.</h2><p>Платформа должна помогать сайту решать задачу сегодня и не мешать его развитию завтра. Выбираем её после разбора структуры, ассортимента, ролей команды и нужных интеграций.</p></div></div><div className={styles.techMap}><div className={styles.techCore}><span>Что должен уметь сайт</span><strong>Работать на продажи сегодня и развиваться дальше.</strong></div><article><span>01</span><h3>React / Next.js</h3><p>Для индивидуальной логики, высокой скорости работы и интерфейсов, которые развиваются вместе с бизнесом.</p></article><article><span>02</span><h3>WordPress</h3><p>Когда команде важно самостоятельно работать с согласованным содержанием сайта и развивать разделы без сложного технического процесса.</p></article><article><span>03</span><h3>1С-Битрикс</h3><p>Когда сайт должен учитывать существующую среду бизнеса, сложный каталог или согласованные интеграции.</p></article></div><p className={styles.techNote}>Не подбираем платформу ради названия. Подбираем решение под задачу сайта.</p></div></section>

    <section className={styles.crmSection} aria-labelledby="crm-title"><div className={styles.container}><div className={styles.crmHeader}><div><p className={styles.sectionIndex}>05 / Интеграция сайта</p><h2 id="crm-title">Форма передаёт запрос в CRM, если она входит в проект.</h2></div><p>Передаём согласованные поля формы и содержание запроса. Это техническая интеграция сайта; дальнейшую обработку обращения команда настраивает в своей рабочей среде.</p></div><div className={styles.crmRoute} aria-label="Передача согласованных данных формы в CRM"><div><small>01</small><strong>Форма, звонок или чат</strong><span>Точка обращения на сайте</span></div><i aria-hidden="true" /><div><small>02</small><strong>Согласованные поля</strong><span>Контакты и содержание запроса</span></div><i aria-hidden="true" /><div className={styles.crmDestination}><small>03</small><strong>CRM</strong><span>Запрос передан в рабочую среду</span></div></div></div></section>

    <section className={styles.readiness} aria-labelledby="readiness-title"><div className={styles.container}><div className={styles.readinessPanel}><div className={styles.readinessCopy}><p className={styles.readinessIndex}>06 / После запуска</p><h2 id="readiness-title">Сайт готов к работе и развитию после запуска.</h2><p>Собираем основу, с которой удобно работать команде: понятные страницы, проверенные сценарии и материалы для дальнейшей поддержки.</p></div><ul className={styles.readinessList}><li><span>01</span><div><h3>Адаптивные состояния</h3><p>Для разных экранов и рабочих устройств.</p></div></li><li><span>02</span><div><h3>Страницы и компоненты</h3><p>Понятная структура и согласованное содержание.</p></div></li><li><span>03</span><div><h3>Техническая аккуратность</h3><p>Производительность и проверка ключевых сценариев.</p></div></li><li><span>04</span><div><h3>Передача и поддержка</h3><p>Доступы и материалы для дальнейшей работы.</p></div></li></ul><aside className={styles.seoBridge} aria-labelledby="seo-title"><p>SEO / Подготовка сайта</p><h3 id="seo-title">Закладываем основу для SEO-продвижения.</h3><div><p>При проектировании сайта учитываем структуру страниц, семантическую разметку, metadata, мобильную версию, скорость загрузки и техническую доступность для индексации. Это подготовка сайта к продвижению, а не обещание позиций или трафика.</p><Link href="/services/marketing" className={styles.seoLink}>SEO-продвижение и работа со спросом — в разделе «Маркетинг». <ActionArrow /></Link></div></aside></div></div></section>

    <section className={styles.designBridge} aria-labelledby="design-title"><div className={styles.container}><div className={styles.designCopy}><p className={styles.sectionIndex}>07 / Дизайн и выбор</p><h2 id="design-title">Дизайн помогает понять предложение и сделать выбор.</h2><p>Проектируем дизайн сайта под бизнес, аудиторию и сценарий покупки. Выстраиваем иерархию, показываем главное, упрощаем путь к нужному действию и собираем адаптивные состояния для разных экранов.</p><Link href="/services/design" className={styles.designLink}>Нужен самостоятельный дизайн-этап? Перейти к дизайну <ActionArrow /></Link></div><div className={styles.designBoard} aria-label="Схема дизайна сайта: предложение, выбор и следующий шаг"><div><small>Предложение</small><b /><b /><b /></div><div><small>Выбор</small><i /><i /><i /></div><div><small>Следующий шаг</small><strong>Обсудить задачу</strong></div><p>Desktop · mobile · единый интерфейс</p></div></div></section>

    <section className={styles.deliverables} aria-labelledby="deliverables-title"><div className={styles.container}><div className={styles.deliverablesHeader}><p className={styles.sectionIndex}>08 / Результат проекта</p><div><h2 id="deliverables-title">Готовый сайт, подключённый к работе бизнеса.</h2><p>Передаём не отдельные файлы, а согласованный результат: сайт, точки обращения, нужные связи и материалы, с которыми команда может работать дальше.</p></div></div><div className={styles.deliveryMap}><div className={styles.deliveryCore}><span>Результат</span><h3>Готовый сайт</h3><small>Структура · дизайн · разработка</small></div><div className={styles.deliveryPages}><span>01</span><h3>Структура и страницы</h3><small>Адаптивный дизайн и сценарии выбора</small></div><div className={styles.deliveryForms}><span>02</span><h3>Обращения и интеграции</h3><small>Формы и согласованные связи</small></div><div className={styles.deliveryOperations}><span>03</span><h3>Работа после запуска</h3><small>Согласованные интеграции — если входят в проект</small></div><div className={styles.deliveryHandoff}><span>04</span><h3>Доступы и материалы передачи</h3><small>Основа для поддержки и дальнейшего развития</small></div><i className={styles.deliveryLineOne} aria-hidden="true" /><i className={styles.deliveryLineTwo} aria-hidden="true" /></div></div></section>
    <section className={styles.caseSection} aria-labelledby="case-title"><div className={styles.container}><div className={styles.caseGrid}><div className={styles.caseVisual}><Image src="/cases/oss-desktop-v1.webp" alt="Каталог ОборонСпецСплав с промышленным металлопрокатом" fill loading="eager" sizes="(max-width: 760px) calc(100vw - 40px), (max-width: 1040px) 58vw, 760px" /></div><div className={styles.caseCopy}><p className={styles.sectionIndex}>Кейс / ОборонСпецСплав</p><h2 id="case-title">Сложный B2B-ассортимент — до предметного запроса.</h2><p>Для ОборонСпецСплава собрали структуру каталога, поиск продукции и путь до связи с менеджером.</p><p>Посетитель может найти нужную продукцию, сориентироваться в ассортименте и перейти к предметному обращению.</p><Link href="/cases/oss" className={styles.caseLink}>Открыть кейс <ActionArrow /></Link></div></div></div></section>
    <section className={styles.startSection} aria-labelledby="start-title"><div className={styles.container}><div className={styles.startPanel}><div><p className={styles.sectionIndex}>Следующий шаг</p><h2 id="start-title">Нужен сайт, который работает на продажи?</h2></div><div className={styles.startCopy}><p>Расскажите, что вы продаёте, как сейчас приходят обращения и что должен изменить новый сайт.</p><a href="#contact-dialog" data-contact-dialog className={styles.finalAction}>Обсудить проект <ActionArrow /></a><Link href="/process" className={styles.processLink}>Как строится работа <span aria-hidden="true">→</span></Link></div></div></div></section>
  </main>;
}
